name: Export PDF

on:
  push:
    branches:
      - main
      - actions/**

jobs:
  export-pdf:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.texlive
        key: ${{ runner.os }}-texlive-${{ hashFiles('**/texlive.lst') }}

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra

    - name: Convert Markdown to PDF
      run: |
        for file in resumes/*.md; do
            pandoc -f markdown -t latex --include-in-header=.github/workflows/header.tex -V geometry:margin=1in -V "footer-includes=" -V "mainfont: Roboto" -V "mainfontoptions: ItalicFont=Roboto-Italic" -o "${file%.md}.pdf" "$file"
        done

    - name: Upload PDF artifacts
      uses: actions/upload-artifact@v2
      with:
        name: exported-pdf
        path: resumes/*.pdf
